# Generated by Django 5.2.1 on 2025-05-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0002_remove_department_doctor_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialty',
            field=models.ManyToManyField(blank=True, null=True, related_name='specialty_doctor', to='system_app.specialty'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, null=True),
        ),
    ]
