# Generated by Django 5.2.1 on 2025-05-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0003_alter_userprofile_email_alter_userprofile_specialty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('был в приеме', 'был в приеме'), ('в ожидании', 'в ожидании'), ('отменен', 'отменен')], max_length=24)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to='system_app.patient')),
            ],
        ),
    ]
