# Generated by Django 5.2.1 on 2025-05-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0004_historyrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
